#!/bin/bash
set -euo pipefail

mem_use=$(free | awk '/Mem:/{ printf "%.0f", (($2 - $7) / $2) * 100 }')

color='#ffffff'
[ ${mem_use} -gt 70 ] && color='#ffd966'
[ ${mem_use} -gt 90 ] && color='#dd0000'

printf '\uf538 <span color="%s">%.0f%%</span>\n' ${color} ${mem_use}
