#!/bin/bash
set -euo pipefail

state=$(mmcli -m any -J 2>/dev/null | jq -r .modem.generic.state)
color="#00ff00"

[[ -n $state ]] || {
  state="unknown"
  color="#333333"
}

printf "\uf690 <span color=\"%s\">%s</span>\n" ${color} ${state}
