#!/usr/bin/env python

import re
import subprocess

CRIT = 70.0


def main():
    sensors = subprocess.check_output(['sensors', '-u']).decode('utf-8')

    max_temp = 0.0
    for line in sensors.split('\n'):
        if not re.match(r'.*temp._input:.*', line):
            continue
        temp = float(line.split(':')[1])

        if temp > max_temp:
            max_temp = temp

    color = '#ffffff'
    if max_temp > CRIT:
        color = '#dd0000'

    text = '\uf2c7 <span color="{}">{:.1f}°C</span>'.format(color, max_temp)

    print(text)


if __name__ == '__main__':
    main()
